### PR TITLE
Do a bunch of cleanups

### PR DESCRIPTION
**Pull request by tcharding**
This is the first 4 patches from #142, pushing up separately because that PR is quite complicated to review well and these cleanups are unrelated.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you find a citation for the `expect` convention? A quick search suggests "there is no convention" and when written this way the error messages don't make sense.

**Comment by tcharding** [comment]
Oh its definitely a convention, its one of the first ones I remember learning that I disagreed with when I first started Rusting. I patched an open source library with it too (yep I was that guy).  I'll go digging for you ... hold the phone, the docs for `Result` literally use an `expect` with "failed to write message" - that is core enough to ignore this once-read-about convention IMO - WIN.

**Comment by tcharding** [comment]
Dropped the last patch (the `expcet` convention one).

**Review by apoelstra — APPROVED** [review]
ACK 8426386b845740cff41520ad56fa086fc2640bdf

**Pull request merged**
