### PR TITLE
benchmarks: restore benchmarks

### PR DESCRIPTION
**Pull request by apoelstra**
In #128 we dropped the benchmarks. They can be restored with only minor tweaks, so do so.

### CODE REVIEW

**Comment by apoelstra** [comment]
CI failure is just because nightly rustc has introduced a new `Freeze` trait which appears in the check-API check. There is a commit to fix this in #180 which I won't copy into here to avoid rebase trouble.

**Review by tcharding — APPROVED** [review]
ACK 82a577d4a471317df6500bd6172813f7cd4c10d7

**Comment by apoelstra** [comment]
cc @clarkmoody this is a quick/easy PR. Can you do a quick review?

Alternately, would you be okay with my merging things here with only ACKs from @tcharding?

**Comment by tcharding** [comment]
Needs api files updating @apoelstra

**Comment by tcharding** [comment]
Also I've emailed Clark to see what is the status here and on #180.

**Review by clarkmoody — APPROVED** [review]
ACK 82a577d4a471317df6500bd6172813f7cd4c10d7

**Comment by apoelstra** [comment]
Rebased, added a one-line warning fix from my `error-correction-2` branch, and also added a benchmark for parameter generation.

**Review by clarkmoody — APPROVED** [review]
ACK e0b95f1920b2c9176232919f86b0846248262f90

**Pull request merged**
