### PR TITLE
Add "alloc" feature

### PR DESCRIPTION
**Pull request by tcharding**
We would like users to be able to use parts of this library in a `no_std` environment without an allocator. To achieve this add an "alloc" feature and feature gate any code that requires allocation behind.

To test the new feature gating works, and catch regressions, add a crate that uses `bech32` as a dependency with no default features and forces a `no_std` build. (Does not test any code just imports the lib to verify it builds.)

Patch 3 can be moved before patch 2 to verify that the crate does not currently build without an allocator.

Patch 4 adds a minimal `contrib/test.sh` script.

### CODE REVIEW

**Comment by tcharding** [comment]
After reading through #45 I made some changes, primarily: make "std" enable "alloc"

**Comment by tcharding** [comment]
Might need some administration changes, this PR changes CI a bit and its now not running. Not exactly sure what needs doing to resolve.

**Comment by tcharding** [comment]
Changes in force push:
- Added an initial patch to remove `extern crate core` instead of doing it within later patch
- Rebased and fixed the new code to work with new "alloc" feature

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by Ericson2314 — APPROVED** [review]
I put my work on top of this successfully, so I would like to see this merge!

If anyone is concerned they not enough works yet without alloc, that is what the remainder in my PR focuses on.

**Comment by tcharding** [comment]
Rebased and improved test script.

**Comment by tcharding** [comment]
Gentle bump, can I get a review please crew.

**Comment by apoelstra** [comment]
Needs rebase.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 4ab480cecdbfc236ecdaa5493416e13b00ad700d

**Comment by apoelstra** [comment]
Needs rebase again.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 85caa284588f0f5a1832bdec21f693ce62ace0fd

**Pull request merged**
