### PR TITLE
avoid potential double-panic

### PR DESCRIPTION
**Pull request by nappa85**
A drop can be caused by a panic, panicking inside a panic causes a double-panic, therefore an abort

### CODE REVIEW

**Comment by clarkmoody** [comment]
So a panic can cause other `drop` methods to be called normally?

**Comment by nappa85** [comment]
> So a panic can cause other `drop` methods to be called normally?

Stating the official docs https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html#panics
```Given that a panic! will call drop as it unwinds, any panic! in a drop implementation will likely abort.```

**Comment by tcharding** [comment]
Perhaps we should just not write the checksum from the `Drop` implementation, since there is an error that should be checked for, would it not be better for users to manually add the checksum so the error can be checked?

**Comment by clarkmoody** [comment]
> Perhaps we should just not write the checksum from the `Drop` implementation, since there is an error that should be checked for, would it not be better for users to manually add the checksum so the error can be checked?

Yeah that sounds like a better approach. Maybe the write during Drop is a bit too much magic?

**Comment by Kixunil** [comment]
Nah, writing on drop is fine, `BufWriter` from `std` does is too (ignoring errors) and we should probably get inspiration from there. Especially have [`panicked` field](https://doc.rust-lang.org/src/std/io/buffered/bufwriter.rs.html#80)

**Comment by tcharding** [comment]
Needs rebase mate.

**Comment by apoelstra** [comment]
Going to close this, since `Bech32Writer` is being dropped. But thank you!

**Pull request closed without merging**
