### PR TITLE
Reduce line count by merging re-exports

### PR DESCRIPTION
**Pull request by tcharding**
Reduce line count and attribute usage by merging the `hrp` re-exports into a single statement.

Refactor only, no logic changes. Also, this patch does not introduce any changes to the rendered HTML.

### CODE REVIEW

**Comment by apoelstra** [comment]
Could you rebase this on master so that the Cargo.toml in this PR is the same as the one in master? This simplifies my lockfile managament.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 74c876dba72e4382951a048f1bd3d04ac535e766

**Comment by apoelstra** [comment]
It appears this was merged but Github is not recognizing it.

**Pull request closed without merging**
