### PR TITLE
Enable edition 2018

### PR DESCRIPTION
**Pull request by tcharding**
Update the MSRV to Rust 1.41.1 and enable edition 2018.

Should not be merged without rust-bitcoin organization-wide planning on how to go about this upgrade.

~Leaving as draft until rust-bitcoin Taproot release is done.~ 

The Clippy fixes are needed to make the update complete (because we run Clippy in CI in `rust-bech32`), hence this should be squashed into a single commit. Leaving it separate for the first rounds of review.

Discussion: https://github.com/rust-bitcoin/rust-bitcoin/issues/510#issuecomment-881686342

### CODE REVIEW

**Comment by apoelstra** [comment]
concept ACK from me -- though I think we should wait until after we've done the Taproot release for rust-bitcoin so that we know we're ready to increase MSRVs across the board.

**Comment by tcharding** [comment]
Yep, I'm with you. I'll convert this to non-draft PR after release of rust-bitcoin 0.28. Thanks.

**Comment by tcharding** [comment]
cc @clarkmoody, are you ok with this one please?

**Review by clarkmoody — APPROVED** [review]
LGTM :shipit:

**Comment by clarkmoody** [comment]
Released 0.9.0 to crates.io

**Comment by jkczyz** [comment]
Looks like the repo is missing a tag for 0.9.0.

**Comment by clarkmoody** [comment]
> Looks like the repo is missing a tag for 0.9.0.

Tagged [v0.9.0](https://github.com/rust-bitcoin/rust-bech32/releases/tag/v0.9.0).

**Pull request merged**
