### PR TITLE
Implement `std::error::Error::source`

### PR DESCRIPTION
**Pull request by tcharding**
Now that we have MSRV of 1.41.1 we can implement `source` to improve the ergonomics of our errors.

Patch 1 is preparatory cleanup.

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK 5e0bf8a3559fe7c1057c995c653c4389e9269daa

**Review by Kixunil — APPROVED** [review]
ACK b7416fc8274f42af285c4777cb58e3c0cad7c8c1

**Review by clarkmoody — APPROVED** [review]
ACK b7416fc

**Comment by tcharding** [comment]
Changes in force push:
- Update `source` method to include new error variant.

**Review by Kixunil — APPROVED** [review]
ACK 6b8e8f23717e86a46bdee16d2c5ae417893454ad

**Comment by tcharding** [comment]
Force push to trigger CI, no changes.

**Comment by tcharding** [comment]
CI fail is a network error
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.16.3-0ubuntu1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Kixunil** [comment]
@tcharding FYI maintainers can re-run failed jobs without pushing. Just open the details of it and there's a button in top right corner.

**Comment by tcharding** [comment]
I'm not a maintainer on this repo. I'm confident to take on that added responsibility though at @clarkmoody and/or @apoelstra's blessing (preferably both). I will not take any offense if the offer is not taken up.

**Review by apoelstra — APPROVED** [review]
ACK b7416fc8274f42af285c4777cb58e3c0cad7c8c1

**Comment by apoelstra** [comment]
I kicked CI. Let's get some API fixes in and then we'll revisit maintainership. It's fine with me in principle.

**Comment by tcharding** [comment]
Something is wrong with CI, there is a network fail that has been happening for a few days now.

**Comment by tcharding** [comment]
Attempted ci fix in #76

**Comment by apoelstra** [comment]
Merged #76. Wanna rebase this?

**Comment by tcharding** [comment]
Rebased, on other changes.

**Comment by apoelstra** [comment]
lol @tcharding could you fix the `cargo fmt` failure?

**Comment by tcharding** [comment]
Face palm :)

**Review by apoelstra — APPROVED** [review]
ACK 5b520d06b5a7a6585cca2509c9a53313914353be

**Pull request merged**
