### PR TITLE
Add `decode` method for raw decoding

### PR DESCRIPTION
**Pull request by stevenroose**
Export public method to decode into the raw HRP and the data bytes.

### CODE REVIEW

**Comment by stevenroose** [comment]
One quick piece of feedback: do you think it's worth allocating a `String` to return the HRP and case it to lowercase instead of returning the original HRP? We kinda already do that with the `hrp_bytes` that is used for the checksum validation.

**Comment by sgeisler** [comment]
It's probably easier for potential users of this function if it always outputs a lowercase HRP. It could return a `Cow<'a, str>` for that purpose. But maybe we want to generally rethink the ownership of `Bech32` as I wrote in #30? In that case the function could return a minimally owning bech32 struct.

**Comment by stevenroose** [comment]
Superseded by https://github.com/rust-bitcoin/rust-bech32/pull/34. Let's move discussion there.

**Comment by sgeisler** [comment]
Included in #35

**Pull request closed without merging**
