### PR TITLE
Bump version to 0.10.0-beta2

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for doing another beta release add a changelog entry and bump the version.

### CODE REVIEW

**Comment by apoelstra** [comment]
Unless I'm crazy, this bumps the version to 0.10.0 :)

**Comment by tcharding** [comment]
No you are not crazy, I am just totally useless today.

**Review by apoelstra — APPROVED** [review]
ACK 7dc7f0afc8f4e37af60151a2a0e38612471d244e

**Comment by apoelstra** [comment]
Yanked. Apparently cargo automatically pulls this in place of `-beta` which breaks compilation forr rust-bitcoin :roll_eyes:. So we need a different name. Maybe `-gamma`?

**Comment by apoelstra** [comment]
https://crates.io/crates/clap/versions looks like clap was using `beta.0`, `beta.1`, `beta.2` etc. Let's try this?

**Pull request merged**
