### PR TITLE
`impl WriteBase32 for Vec<u5>` show cannot fail

### PR DESCRIPTION
**Pull request by Ericson2314**
Use void::Void, which in uninhabited, to do this.

### CODE REVIEW

**Comment by sgeisler** [comment]
Hi, great idea! Afaik constructing a void type is quite straight forward, maybe we could implement it ourselves instead of relying on a dependency? Otherwise this would increase the auditing effort/attack surface.

**Comment by Ericson2314** [comment]
Implementing ones own `Void` does mean that one looses out from `From` instances in other crates. `!` has finally been stabilized, so hopefully this problem goes away soon.

**Comment by sgeisler** [comment]
Pinning the version tightly without a cryptographic hash of the crate is even worse imo. You loose out on bug fixes while it's still possible to get pwned (not by the author, but crates.io or AWS). So how badly is this feature needed irl (I totally see the theoretical appeal)? Can we just wait for `!` instead? 

The only drawback seems to be unnecessary `unwraps` and less compiler optimization. If there is an argument to be made that either of these is a major inconvenience I could see this being merged. Otherwise we try hard to minimize dependencies.

@clarkmoody what do you think? It's kind of a borderline case imo since we''d use a big part of a very small crate, so the additional auditing effort would be small compared to inlining it.

**Comment by Ericson2314** [comment]
> Pinning the version tightly without a cryptographic hash of the crate is even worse imo.

Yes, sorry, that is absolutely correct. Would be ideal if there is a tool to go over a lockfile with some sort of audit whitelist.

**Comment by apoelstra** [comment]
Yeah, unfortunately by implementing this ourselves we'd lose a ton of interop benefits.

I'm pretty tempted by this, even though I'm generally pretty dependency-averse.

**Comment by clarkmoody** [comment]
If we can wait on stabilization of `!` and get this for free when we bump minimum version down the line, I think that might be better than adding a dependency.

**Comment by sgeisler** [comment]
That might be a very long time to wait :( If it got stabilized in the next version that doesn't mean we can use it the next time we bump our min version (e.g. if we want to target debian stable/oldstable that could take some time to propagate there).

**Comment by Ericson2314** [comment]
What about using [`core::convert::Infallible`](https://doc.rust-lang.org/core/convert/enum.Infallible.html), which is intended to become `!`?

**Comment by RCasatta** [comment]
> What about using [`core::convert::Infallible`](https://doc.rust-lang.org/core/convert/enum.Infallible.html), which is intended to become `!`?

I am afraid Infallible is introduced in 1.34 which is still after our MSRV 1.29

**Comment by TheBlueMatt** [comment]
I think we can just bump the MSRV. There was some previous agreement to move the rust-bitcoin ecosystem to 1.36 once it was 2 years old (which it is now). https://github.com/rust-bitcoin/rust-bitcoin/issues/510#issuecomment-827026821

**Comment by Ericson2314** [comment]
RIght, it's small extra dep vs bump MSRV. I am fine either way, just please pick your poison :).

**Comment by Ericson2314** [comment]
If you do end up going the bumping MSRV route, I will happily fix up https://github.com/rust-bitcoin/rust-bech32/pull/44 to switch to newer edition too.

**Comment by clarkmoody** [comment]
I would rather bump MSRV than add a dependency.

**Comment by Ericson2314** [comment]
OK that is done instead.

**Comment by apoelstra** [comment]
Heads up that rust-bitcoin is at least one major version away from also bumping its MSRV, so if we merge this now, it may complicate our dependency management for a bit.

**Comment by tcharding** [comment]
The changes to `lib.rs` in this PR can be directly applied on top of #57.

**Comment by tcharding** [comment]
We now have an MSRV of 1.41.1 so can use `Infallible`. The changes to `lib.rs` in this PR can be directly applied on top of `master`.

**Comment by Ericson2314** [comment]
Updated!

**Review by apoelstra — APPROVED** [review]
utACK cc50e7d509f2887020a753a42b9eaba8907eac3b

**Review by tcharding — APPROVED** [review]
ACK cc50e7d509f2887020a753a42b9eaba8907eac3b

**Comment by Ericson2314** [comment]
Thanks!

**Pull request merged**
