### PR TITLE
Add no_std

### PR DESCRIPTION
**Pull request by RCasatta**
It's different from #46 because MSRV with std is still 1.29, while for no_std the MSRV is 1.36 because it uses `alloc`.

Includes a test in CI building a no_std embedded program (the test requires nightly because of the allocator used). ~~The embedded test is not run (only built) because there are issues with emulating arm on github action env.~~

### CODE REVIEW

**Comment by RCasatta** [comment]
last force-push reduced the files needed for the embedded CI test as suggested in https://github.com/rust-bitcoin/bitcoin_hashes/pull/120#discussion_r611744355

**Comment by RCasatta** [comment]
the latest push actually execute (not just build) the embedded process in CI

**Review by devrandom — APPROVED** [review]
ACK

Tested as part of my upcoming no_std PR for rust-bitcoin on both 1.29 and stable.

**Comment by RCasatta** [comment]
Hi devrandom, there is a relevant discussion on https://github.com/rust-bitcoin/bitcoin_hashes/pull/120 about how to implement no_std on rust-bitcoin, in particular for handling `io::Read` and `io::Write`. I am working on the PR on bitcoin_hashes

**Review by TheBlueMatt — APPROVED** [review]

**Review by sgeisler — APPROVED** [review]
utACK 9921ca87db6c645270f5e05f0e63bb90b0d9b08c

Thank you for pushing `no_std` forward, I hope we'll be able to build HW wallets one day using rust-bitcoin :smiley:

**Review by clarkmoody — APPROVED** [review]
Thanks for making this work 🎉

**Pull request merged**
