### PR TITLE
Implement `TryFrom`

### PR DESCRIPTION
**Pull request by tcharding**
Now that we have MSRV 1.41.1 we can use `TryFrom`. Implement TryFrom<u8> for `u5` with the code that was in `try_from_u8`.

### CODE REVIEW

**Comment by tcharding** [comment]
Changes in force push: Remove initial patch (which should never have been here).

**Comment by tcharding** [comment]
Rebase and run formatter.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Comment by tcharding** [comment]
Gentle bump, can I get a review please crew.

**Comment by apoelstra** [comment]
utACK 0c3059c3361fdbd0238d6e5c39bb28622dccf131 but needs rebase.

**Comment by tcharding** [comment]
GitHub actions CI is does not appear to be running on this repo, do you have perms to check the settings please @apoelstra?

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK bd651bbf2cb918724bdce5f189d40672e9b6b279

**Pull request merged**
